#!/bin/bash

#Create User
useradd -m -s /bin/rbash tooluser
usermod -aG docker tooluser
echo "Enter password for low privilege user (tooluser):"
read -s user_pass
echo -e "$user_pass\n$user_pass\n" | passwd tooluser
rm /home/tooluser/.*
mkdir -p /home/tooluser/bin
chown root:root /home/tooluser/bin
chmod -R 755 /home/tooluser/bin
echo "PATH=\$HOME/bin" > /home/tooluser/.bashrc
chown root:root /home/tooluser/.bashrc
chmod 755 /home/tooluser/.bashrc
mkdir -p /home/tooluser/out
chown tooluser:tooluser /home/tooluser/out
chmod -R 755 /home/tooluser/out

#Create Environment
cp Dockerfile /home/tooluser/Dockerfile
chmod 755 /home/tooluser/Dockerfile
cp the_scan /home/tooluser/the_scan
chmod 755 /home/tooluser/the_scan

sudo -u tooluser podman build -t toolserver /home/tooluser/
sudo -u tooluser podman run -d --network bridge --cap-add NET_RAW -v /home/tooluser/out:/home --name toolserver toolserver
#sudo -u tooluser podman run -it --entrypoint /bin/bash --network=bridge --cap-add=NET_RAW --name toolserver toolserver
