#!/bin/bash

#Create User
useradd -m -s /bin/rbash tooluser
usermod -aG docker tooluser
echo "Enter password for low privilege user (tooluser):"
read -s user_pass
echo -e "$user_pass\n$user_pass\n" | passwd tooluser
rm /home/tooluser/.*
mkdir -p /home/tooluser/bin
chown cdoalladmin:cdoalladmin /home/tooluser/bin
chmod -R 755 /home/tooluser/bin
echo "PATH=\$HOME/bin" > /home/tooluser/.bashrc
chown cdoalladmin:cdoalladmin /home/tooluser/.bashrc
chmod 755 /home/tooluser/.bashrc
mkdir -p /home/tooluser/out
chown cdoalladmin:cdoalladmin /home/tooluser/out
chmod -R 755 /home/tooluser/out

#Create Environment
cp Dockerfile /home/tooluser/Dockerfile
chmod 755 /home/tooluser/Dockerfile
cp the_scan /home/tooluser/the_scan
chmod 755 /home/tooluser/the_scan

#Change user and run
sudo -i -u tooluser bash << EOF
echo "Changed user to \$(whoami)"
docker build -t toolserver /home/tooluser/
docker run --cpus="3.5" -v /home/tooluser/out:/home --name toolserver -d toolserver
EOF

#sudo -u tooluser docker run -it --entrypoint /bin/bash --name toolserver toolserver
